services:
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build:
      context: ./note-kraft-backend
      dockerfile: Dockerfile
    volumes:
      - ./note-kraft-backend:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017"
    depends_on:
      - mongo

  client:
    build:
      context: ./note-kraft
      dockerfile: Dockerfile
    volumes:
      - ./note-kraft:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongo-db:
